name: HTML-CSS-JS CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List project files
      run: ls -la

    # - name: Validate HTML (optional)
    #   uses: Cyb3r-Jak3/html5validator-action@main
